coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 10%
        if_ci_failed: error

  ignore:
    - "**/*_test.go"
    - "**/testing/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
