version: 2

builds:
  - skip: true

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: zoobz-io
    name: aperture
  draft: false
  prerelease: auto
  header: |
    ## What's Changed
  footer: |
    ## Installation
    ```bash
    go get github.com/zoobz-io/aperture@{{ .Tag }}
    ```
